### ISSUE TITLE
这个项目还活动吗？很久没更新了？开始听这个ｆｎ不好使

### ISSUE THREAD

**Issue by crapthings** [floatinghotpot/cordova-plugin-iflyspeech#1]
没有任何反应啊

navigator.speech.startListening

```
    navigator.speech.startListening
        language: "zh_cn"
        accent: "mandarin"
    , (str) ->
        ($ "#debug").val str
```

**Comment by crapthings** [comment]
appid　我已经换了，在官方下了 sdk 复制到 libs 后就　ｂｕｉｌｄ失败了

**Comment by floatinghotpot** [comment]
it's tested working in our project (5 months ago).

for this plugin, we only provide commercial support.

**Comment by crapthings** [comment]
我测试了一下语音合成引擎工作了，可以读取我输入的文字，语音识别部分貌似不工作了，可能和官方sdk更新有关吧。

商业支持　如何联系你们呢，收费的cordova插件是怎么样一个价格呢？

**Comment by floatinghotpot** [comment]
for popular plugin, we charge $20 for each license and provide support.

as this speech plugin is not popular, the average support cost is higher. 
we charge in outsourcing service model, by estimating man-hour. 

please write to rjfun.mobile@gmail.com to discuss more details if interested.

**Comment by crapthings** [comment]
thanks raymond
